#####
## Compose file to run the voting app and dependent services
###

version: '2'

services:
  interlock:
    image: ehazlett/interlock:1.0.1
    command: -D run
    tty: true
    ports:
        - 8080
    environment: 
        INTERLOCK_CONFIG: |
            ListenAddr = ":8080"
            DockerURL = "tcp://54.183.181.250:3375"
            
            [[Extensions]]
            Name = "nginx"
            ConfigPath = "/etc/conf/nginx.conf"
            PidPath = "/etc/conf/nginx.pid"
            MaxConn = 1024
            Port = 80
    volumes:
        - nginx:/etc/conf
        - /var/tmp/config.toml:/bin/config.toml

  nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/conf/nginx.conf
    ports:
        - 80:80
    labels:
        - "interlock.ext.name=nginx"
    links:
        - interlock:interlock
    volumes:
        - nginx:/etc/conf

  web-vote-app:
    image: swarmdemo/web-vote-app
    ports:
      - "80"
    environment:
      WEB_VOTE_NUMBER: "01"
    labels:
      - "interlock.hostname=webvote"
      - "interlock.domain=local"

  vote-worker:
    image: swarmdemo/vote-worker
    environment:
      FROM_REDIS_HOST: 1
      TO_REDIS_HOST: 1
    labels:
      - "interlock.hostname=voteworker"
      - "interlock.domain=local"


  results-app:
    image: swarmdemo/results-app
    labels:
      - "interlock.hostname=results"
      - "interlock.domain=local"


  redis01:
    image: redis:3

  store:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg8675309

volumes:
  nginx:
    driver: local
