#####
## Compose file to run the voting app and dependent services
###

version: '2'

services:
  web-vote-app:
    image: swarmdemo/web-vote-app
    expose:
      - 80
    environment:
      WEB_VOTE_NUMBER: "01"

  vote-worker:
    image: swarmdemo/vote-worker
    environment:
      FROM_REDIS_HOST: 1
      TO_REDIS_HOST: 1

  results-app:
    image: swarmdemo/results-app

  redis01:
    image: redis:3

  store:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg8675309
